site_name: sml_small docs
nav:
  - Home: index.md
  - Content: content.md
theme:
  name: mkdocs
  custom_dir: sml_builder/templates/
plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [./sml_small]

